maxima/g0/advection/advectionFuncs-vol-C.mac
maxima/g0/dg_diffusion/diff-vol-C.mac
maxima/g0/gyrokinetic/gkUtil.mac
maxima/g0/lenard_bernstein_operator/gkLBOFuncs-diff-vol.mac
maxima/g0/lenard_bernstein_operator/gkLBOFuncs-drag-vol.mac
maxima/g0/lenard_bernstein_operator/vmLBOFuncs-diff-vol.mac
maxima/g0/lenard_bernstein_operator/vmLBOFuncs-drag-vol.mac
maxima/g0/maxwell/maxwellFuncs-vol-C.mac
maxima/g0/maxwell/ms-maxwell-vol.mac
maxima/g0/vlasov/ms-vlasovMaxwell-vol-C.mac
maxima/g0/vlasov/ms-vlasovPoisson-vol-C.mac
maxima/g0/vlasov/ms-vlasovStream-vol-C.mac
maxima/g0/vlasov/vlasovMaxwellFuncs-vol-C.mac
maxima/g0/vlasov/vlasovMaxwellSRFuncs-vol-C.mac
maxima/g0/vlasov/vlasovPoissonFuncs-vol-C.mac
maxima/g0/vlasov/vlasovSRStreamFuncs-vol-C.mac
maxima/g0/vlasov/vlasovStreamFuncs-vol-C.mac

This addresses issue 56 in gkylzero: https://github.com/ammarhakim/gkylzero/issues/56
Previously kernels 
- did not incorporate the factors of 2p+1 for advection terms
- incorporated a factor of ((p+1)^2)/(2p+1) for diffusion terms
and we multiplied the CFL frequency by 2p+1 at the app level.
In this commit we
- Incorporate the 2p+1 factor for advection terms in vlasov,  gyrokinetic, and LBO volume kernels.
- Modify the factor to (p+1)^2 in diffusion terms of LBO volume kernels.
- Incorporate a factor of 2/dx that was missing in advection equation volume terms.
- Incorporate a factor of (p+1)^2 in dg_diffusion volume terms that was missing.
I checked
rt_lbo_vlasov_relax_1x2v_p1
rt_lbo_vlasov_relax_1x2v_p2
rt_neut_lbo_sod_shock_2v
rt_sheath_1v
rt_twostream
rt_twostream_p1
rt_weibel_4d …

New calculation of CFL frequency

---

maxima/g0/lenard_bernstein_operator/gkLBOFuncs-diff-boundary-surf.mac
maxima/g0/lenard_bernstein_operator/gkLBOFuncs-diff-surf.mac
maxima/g0/lenard_bernstein_operator/gkLBOFuncs-diff-vol.mac
maxima/g0/lenard_bernstein_operator/gkLBOFuncs-drag-boundary-surf.mac
maxima/g0/lenard_bernstein_operator/gkLBOFuncs-drag-surf.mac
maxima/g0/lenard_bernstein_operator/gkLBOFuncs-drag-vol.mac
maxima/g0/lenard_bernstein_operator/ms-gkLBO-header.mac
maxima/g0/lenard_bernstein_operator/ms-vmLBO-header.mac
maxima/g0/lenard_bernstein_operator/vmLBOFuncs-diff-boundary-surf.mac
maxima/g0/lenard_bernstein_operator/vmLBOFuncs-diff-surf.mac
maxima/g0/lenard_bernstein_operator/vmLBOFuncs-diff-vol.mac
maxima/g0/lenard_bernstein_operator/vmLBOFuncs-drag-boundary-surf.mac
maxima/g0/lenard_bernstein_operator/vmLBOFuncs-drag-surf.mac
maxima/g0/lenard_bernstein_operator/vmLBOFuncs-drag-vol.mac
maxima/g0/prim_moments/CrossPrimMomsLBO-vlasov-with-fluid.mac
maxima/g0/prim_moments/CrossPrimMomsLBO.mac
maxima/g0/prim_moments/ms-gkPrimMoments-header.mac
maxima/g0/prim_moments/ms-vlasovPrimMoments-header.mac

The primitive moments u and vtSq are nearly always needed together, in cross primitive moment updaters or LBO kernels. So it makes sense to just put them into a single gkyl_array. This simplifies the Apps, doesn't change kernels much, and simplifies inter-species communication.
g0 unit and regression tests pass on both CPU and GPU (although I saw a weird nvlink warning, see gkylzero's 96dda276333efda82b0f4d77bdf4622e693f0e08). g2 vmLBO and gkLBO regression tests also pass.

Combine primitive moments u and vtsq

---

maxima/g0/lenard_bernstein_operator/gkLBOFuncs-diff-boundary-surf.mac
maxima/g0/lenard_bernstein_operator/gkLBOFuncs-diff-surf.mac
maxima/g0/lenard_bernstein_operator/gkLBOFuncs-drag-boundary-surf.mac
maxima/g0/lenard_bernstein_operator/gkLBOFuncs-drag-surf.mac
maxima/g0/lenard_bernstein_operator/ms-gkLBO-diff-boundary-surf.mac
maxima/g0/lenard_bernstein_operator/ms-gkLBO-diff-surf.mac
maxima/g0/lenard_bernstein_operator/ms-gkLBO-drag-boundary-surf.mac
maxima/g0/lenard_bernstein_operator/ms-gkLBO-drag-surf.mac
maxima/g0/lenard_bernstein_operator/ms-vmLBO-diff-boundary-surf.mac
maxima/g0/lenard_bernstein_operator/ms-vmLBO-diff-surf.mac
maxima/g0/lenard_bernstein_operator/ms-vmLBO-drag-boundary-surf.mac
maxima/g0/lenard_bernstein_operator/ms-vmLBO-drag-surf.mac
maxima/g0/lenard_bernstein_operator/vmLBOFuncs-diff-boundary-surf.mac
maxima/g0/lenard_bernstein_operator/vmLBOFuncs-diff-surf.mac
maxima/g0/lenard_bernstein_operator/vmLBOFuncs-drag-boundary-surf.mac
maxima/g0/lenard_bernstein_operator/vmLBOFuncs-drag-surf.mac
maxima/g0/utilities.mac

This goes with gkylzero pull request #121: https://github.com/ammarhakim/gkylzero/pull/121
Some simplifications had been done to the diffusion term in the LBO, which broke energy conservation for p>1. This PR corrects that (see the link above for an explanation).
Further optimization of LBO diffusion terms is possible, but we leave that for future work.

Fix LBO energy conservation for p>1

---

maxima/g0/ambi_bolt_potential/ambi_bolt_potential_funcs.mac
maxima/g0/ambi_bolt_potential/ms-ambi_bolt_potential-header.mac
maxima/g0/ambi_bolt_potential/ms-ambi_bolt_potential.mac
maxima/g0/gyrokinetic/gkFuncs-vol.mac
maxima/g0/gyrokinetic/gkUtil.mac
maxima/g0/nodal_operations/ms-basis_surf_quad_upwind_accepted_results.mac

This is for use in 1x gyrokinetic simulations. In principle the solvers are written so the potentially work in 3x as well, although we haven't tested that option.
We tested it with mirror simulations and produced identical results (i.e. phi) to the previous g2 simulations, up to a point. After a certain time (t~10 microsec) the simulation becomes unstable, but we think this is due to subtleties in gkhybrid basis and will explore that in another branch.

Implement ambipolar Boltzmann electron field solver model

---

maxima/g0/recovery-calc/recovery-1cell.mac
maxima/g0/recovery-calc/recovery-2cell.mac
maxima/g0/recovery-calc/recovery-face.mac
maxima/g0/recovery-unit.mac

Adding more options to the 1-cell recovery. It is now possible to recover a new representation in a cell that matches recovered values and slopes at the interfaces but does _not_ have to be weakly equal to the moments in the cell.

Limited 1-cell recovery options

---

maxima/g0/moments/gkIntMomentsFuncs.mac
maxima/g0/moments/gkMomentsFuncs.mac
maxima/g0/moments/ms-gk-moment-header.mac

This is a moments option for gyroknietics that computes M0, M1, M2par and M2perp at the same time.
This goes with PR #474 in gkylzero: https://github.com/ammarhakim/gkylzero/pull/474

Add FourMoments option for gyrokinetics

---

maxima/g0/translate_dim/ms-trans_dim-header.mac
maxima/g0/translate_dim/ms-trans_dim.mac
maxima/g0/translate_dim/trans_dim.mac

Kernels for an updater that translates the DG coefficients of a lower dimensionality field to those of a higher dimensionality field (e.g. for loading 2x distributions as ICs in a 3x sim).
This goes with PR 479 in gkylzero: https://github.com/ammarhakim/gkylzero/pull/479

Kernels to translate dimensionality of a field

---

maxima/g0/canonical_pb/canonical-alpha-surf.mac
maxima/g0/canonical_pb/canonical-pressure-vars.mac
maxima/g0/canonical_pb/canonical-vol.mac
maxima/g0/canonical_pb/canonicalFuncs-surf.mac
maxima/g0/canonical_pb/canonicalMomentFuncs.mac
maxima/g0/canonical_pb/canonicalUtils.mac
maxima/g0/canonical_pb/ms-canonical-pb-alpha-surf.mac
maxima/g0/canonical_pb/ms-canonical-pb-header.mac
maxima/g0/canonical_pb/ms-canonical-pb-moment-header.mac
maxima/g0/canonical_pb/ms-canonical-pb-moments.mac
maxima/g0/canonical_pb/ms-canonical-pb-pressure-vars.mac
maxima/g0/canonical_pb/ms-canonical-pb-surf.mac
maxima/g0/canonical_pb/ms-canonical-pb-vol.mac

This is a combination of two PR's in G0 meant to add hybrid and tensor basis to the canonical bracket updater. As well as the computation of an energy moment for can-pb directly from the energy moment.
For hybrid/tensor basis see: [G0 PR#512](https://github.com/ammarhakim/gkylzero/pull/512)
For energy moment see: [G0 PR#491](https://github.com/ammarhakim/gkylzero/pull/491)

Can-pb Tensor/Hybrid Basis and Energy Moment Calc

---

maxima/g0/canonical_pb/canonical-alpha-surf.mac
maxima/g0/canonical_pb/canonical-pressure-vars.mac
maxima/g0/canonical_pb/canonical-vol.mac
maxima/g0/canonical_pb/canonicalFuncs-surf.mac
maxima/g0/canonical_pb/canonicalUtils.mac
maxima/g0/canonical_pb/ms-canonical-pb-alpha-surf.mac
maxima/g0/canonical_pb/ms-canonical-pb-header.mac
maxima/g0/canonical_pb/ms-canonical-pb-moment-header.mac
maxima/g0/canonical_pb/ms-canonical-pb-moments.mac
maxima/g0/canonical_pb/ms-canonical-pb-pressure-vars.mac
maxima/g0/canonical_pb/ms-canonical-pb-surf.mac
maxima/g0/canonical_pb/ms-canonical-pb-vol.mac

Generates the kernels to allow for ignorable coordinates in the can-pb species.
See [G0 PR](https://github.com/ammarhakim/gkylzero/pull/536) and associated DR for more details.

Added 1x2v, 1x3v, 2x3v kernels to the can-pb species

---

maxima/g0/skin_surf_from_ghost/ms-ssfg-header.mac
maxima/g0/skin_surf_from_ghost/ms-ssfg.mac
maxima/g0/skin_surf_from_ghost/ssfg.mac

Maxima for the skin_surf_from_ghost updater in gkylzero. This updater:
1. Evaluates the ghost at the "basis" nodes on the skin-ghost boundary.
2. Sets the value of the skin at the "basis" nodes on the skin-ghost boundary to equal the ghost at these same locations. Leaves the value at the nodes not on the "basis" nodes fn the skin-ghost boundary untouched.
3. Performs a nodal to modal transformation to reconstruct the skin's modal representation.
This meant to be used for enforcing the TS BC of phi on the boundary surface after we use the TS updater to fill the ghost cell ([PR 576 in gkylzero](https://github.com/ammarhakim/gkylzero/pull/576)).

Skin surf from ghost Maxima

---

maxima/g0/bin_op/binOp-mul-cross.mac
maxima/g0/dg_interpolate/dg_interp.mac
maxima/g0/dg_interpolate/ms-dg_interp-header.mac
maxima/g0/dg_interpolate/ms-dg_interp.mac
maxima/g0/gk-sheath/sheath-1x1v.mac
maxima/g0/out-scripts.mac
maxima/g0/prim_moments/CrossPrimMomsLBO-vlasov-with-fluid.mac
maxima/g0/prim_moments/CrossPrimMomsLBO.mac

These kernels are meant to be used in interpolating a DG field onto another grid with the same extents but different number of cells. It assumes that one is going to do 1D interpolation at a time. General multi-D interpolation kernels are in principle possible but the Maxima kernels that come out of that are too big; see earlier commits, commits to the g2 Maxima or the g2 repo for attempts at multi-D interpolation kernels.
This goes with PR 574 in gkylzero: https://github.com/ammarhakim/gkylzero/pull/574

Maxima for the dg_interpolate operator

---

maxima/g0/array_average/array_average.mac
maxima/g0/array_average/ms-array_average.mac

New Maxima script and function are designed to compute the kernel required for computing array average of `gkyl_array`.
The kernels are written for arrays from 1x to 3x and p=1,2. The race condition in GPU runs is handled by an atomicadd inside the kernel.
PR in gkylzero: https://github.com/ammarhakim/gkylzero/pull/558
DR in gkylzero: https://github.com/ammarhakim/gkylzero/issues/557

Kernels generator for the array_average updater in g0

---

maxima/g0/gyrokinetic/gkFuncs-surf.mac

The maxima was not handling the dualmag factor correctly in 1x and 2x. Thanks @tnbernard and @JunoRavin for spotting this.
This goes with [PR 617 in gkylzero](https://github.com/ammarhakim/gkylzero/pull/617).

Fix the boundary flux kernels for GK

---

maxima/g0/canonical_pb/canonicalUtils.mac
maxima/g0/canonical_pb/fluid-canonical-alpha-surf.mac
maxima/g0/canonical_pb/fluid-canonical-funcs-surf.mac
maxima/g0/canonical_pb/fluid-canonical-funcs-vol.mac
maxima/g0/canonical_pb/fluid-canonical-source.mac
maxima/g0/canonical_pb/ms-canonical-pb-header.mac
maxima/g0/canonical_pb/ms-fluid-canonical-pb-alpha-surf.mac
maxima/g0/canonical_pb/ms-fluid-canonical-pb-source.mac
maxima/g0/canonical_pb/ms-fluid-canonical-pb-surf.mac
maxima/g0/canonical_pb/ms-fluid-canonical-pb-vol.mac

such as incompressible Euler, Hasegawa-Mima, and Hasegawa-Wakatani. Goes with gkylzero PR https://github.com/ammarhakim/gkylzero/pull/610

Corresponding Maxima for the extension of Vlasov fluid species to simulate canonical Poisson bracket fluid equations

---

maxima/g0/moments/gkIntMomentsFuncs.mac

It is a very minor modification where we just split the three-moments moments function (that computes M0, M1 and M2) into separated functions that we call to generate the single integrated moment kernels.
We want to use the integrated M2 moments for the source adaptation in gkylzero this [DR](https://github.com/ammarhakim/gkylzero/issues/631).

Add functions to calculate integrated moments M0, M1, and M2.

---

maxima/g0/dg_diffusion_fluid/diffFuncs-fluid-boundary-surf.mac
maxima/g0/dg_diffusion_gyrokinetic/diffFuncs-gyrokinetic-boundary-surf.mac
maxima/g0/dg_diffusion_vlasov/diffFuncs-vlasov-boundary-surf.mac

There was a curly braces closing an if-statement that was printed in the wrong place, so our kernels looked like
```
if (edge == -1) {
...
}
else {
...
out[0] = ...
out[1] = ...
...
}
```
instead of 
```
if (edge == -1) {
...
}
else {
...
}
out[0] = ...
out[1] = ...
...
```
so diffusion wasn't applied in the lower skin cell.

Fix a bug in diffusion boundary surf kernels

---

maxima/g0/ambi_bolt_potential/ambi_bolt_potential_funcs.mac
maxima/g0/ambi_bolt_potential/ms-ambi_bolt_potential.mac

Purpose: Support is extended to 2x and 3x for Boltzmann electron simulations. This is needed in the mirror simulations for WHAM. Extensive unit testing is performed.
See https://github.com/ammarhakim/gkylzero/pull/639 for full details

2x and 3x Boltzmann electron kernels

---

maxima/g0/cross_prim_moms/gkCrossPrimMomsBGKFuncs.mac

Now it checks vtsq_sr at each quadrature point individually, and turns off cross collisions if any is negative.

Fix a bug in kernels of BGK cross primitive moments. 

---

maxima/g0/translate_dim/ms-trans_dim-header.mac
maxima/g0/translate_dim/ms-trans_dim.mac
maxima/g0/translate_dim/trans_dim.mac

Previously the translate_dim_gyrokinetic was used to translate the DG coefficients of a lower dimensional distribution, say a 2x2v one, to a higher dimensional one, i.e. 3x2v.
In this PR we generalize this updater, and rename it translate_dim, so that it also works for translating conf-space fields to lower or upper dimensional fields. For projecting down to lower dimensions we generate kernels:
- For each dimension (that can be removed).
- For each location within a cell where the higher dimensional field can be evaluated along along the dimension to be removed, and we support the locations -1, 0 and +1.
This new functionality is used to turn the volume-expansion of the boundary flux into a surface array, see [PR 653 of gkylzero](https://github.com/ammarhakim/gkylzero/pull/653).

Add support for conf-space and other options in translate_dim

---

maxima/g0/gk_neut_hamil/gk-neut-hamil.mac
maxima/g0/gk_neut_hamil/ms-gk-neut-hamil.mac

Adding Maxima scripts that generate the kernels to calculate the hamiltonian for the canonical PB GK neutrals:
H = 0.5*h^ij*w_i*w_j
Here h^ij are equivalent to the gk_geom gij object, which is passed at initialization of this updater. The w_i and w_j are the velocity variables corresponding to the curvilinear coordinate system, in this case vz, vy, vz. The hamiltonian must be continuous, so it is calculated on the nodal values and then returns the modal values. For 1x and 2x there is a reordering of the metric coefficients because the convention of velocity space order always places the ignorable coordinates last. It will assume the following order: 
1x : (z, vz, vx, vy)
2x: (x, z, vx, vz, vy)
3x: (x, y, z, vx, vy, vz)
This requires a reordering of the metric coefficients in the kernel …

Calculate hamiltonian for gk neut can pb
